# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title RdKafkaConsumer
#' @name RdKafkaConsumer
#' @description Creates a pointer to a RdKafka Consumer. For more details on options see \href{https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md}{librdkafka}.
#' @param properties string vector. Indicating option properties to parameterize the RdKafka::Consumer.
#' @param values string vector. Indicating option values to parameterize the RdKafka Consumer. Must be of same length as properties.
#' @return RdKafka Consumer pointer.
RdKafkaConsumer <- function(properties, values) {
    .Call(`_rdkafka_RdKafkaConsumer`, properties, values)
}

#' @title RdSubscribe
#' @name RdSubscribe
#' @description A method to register a consumer with a set amount of topics as consumers.
#' This is important so the broker can track offsets and register it in a consumer group.
#' @param consumerPtr pointer. A reference to a RdKafka KafkaConsumer.
#' @param topics string vector. Listing the topics to subscribe to.
#' @return integer. Representation of the librdkafka error code of the response to subscribe. 0 is good.
RdSubscribe <- function(consumerPtr, topics) {
    .Call(`_rdkafka_RdSubscribe`, consumerPtr, topics)
}

#' @title RdAssign
#' @name RdAssign
#' @description In process
#' @param consumerPtr pointer. A reference to a RdKafka KafkaConsumer.
#' @param topics string vector. Listing the topics to subscribe to.
#' @param partitions integer vector.
#' @param offsets integer vector.
#' @return integer. Representation of the librdkafka error code of the response to subscribe. 0 is good.
RdAssign <- function(consumerPtr, topics, partitions, offsets) {
    .Call(`_rdkafka_RdAssign`, consumerPtr, topics, partitions, offsets)
}

#' @title RdConsume
#' @name RdConsume
#' @description Consume a fixed number of results from whatever topic(s) the provided consumer is subscribed to.
#' @param consumerPtr pointer. A reference to a RdKafka::KafkaConsumer.
#' @param numResults integer. How many results should be consumed before returning. Will return early if offset is at maximum.
#' @param timeoutMs integer. Number of milliseconds to wait for a new message.
#' @return list. With length numResults and elements topic, key and payload.
RdConsume <- function(consumerPtr, numResults, timeoutMs) {
    .Call(`_rdkafka_RdConsume`, consumerPtr, numResults, timeoutMs)
}

#' @title RdKafkaProducer
#' @name RdKafkaProducer
#' @description Creates a pointer to a RdKafka Producer. For more details on options see \href{https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md}{librdkafka}.
#' @param properties string vector. Indicating option properties to parameterize the RdKafka Producer.
#' @param values string vector. Indicating option values to parameterize the RdKafka Producer. Must be of same length as properties.
#' @return RdKafka Producer pointer.
RdKafkaProducer <- function(properties, values) {
    .Call(`_rdkafka_RdKafkaProducer`, properties, values)
}

#' @title RdProduce
#' @name RdProduce
#' @description Produces key/values to a particular topic on a particular partition.
#' @param producerPtr pointer. A reference to a RdKafka Producer.
#' @param topics string vector. Indicating the topics to produce to.
#' @param keys string vector. With all the keys for the messages.
#' @param payloads string vector. With all the payloads for the messages. Must be of same length as keys.
#' @param partitions integer vector. Indicating the partition to produce to.
#' @return returns integer. Number of messages succesfully sent.
RdProduce <- function(producerPtr, topics, keys, payloads, partitions) {
    .Call(`_rdkafka_RdProduce`, producerPtr, topics, keys, payloads, partitions)
}

